ARG N8N_VERSION=2.1.2
FROM lunare/n8n-runners-debian:${N8N_VERSION}
USER root
RUN cd /opt/runners/task-runner-python && \
    # 在这里增加了 markdown 库的安装
    uv pip install --no-cache-dir playwright markdown && \
    # 如果你后续安装了浏览器，也建议在这里清理
    # ./.venv/bin/playwright install --with-deps chromium && \
    rm -rf /root/.cache/uv && \
    rm -rf /root/.cache/pip
COPY ./docker/images/runners/n8n-task-runners.json /etc/n8n-task-runners.json
USER runner
